DEFAULT_HERZOG_HOST = 'euclid'
DEFAULT_HERZOG_PORT = 8001
DEFAULT_KINSKI_PORT = 8002
DEFAULT_WORKING_DIR = '/tmp'
DEFAULT_LOG_DIR     = '/var/log'
DEFAULT_VERBOSITY   = True
HERZOG_LOG_FILENAME = 'herzog.log'
KINSKI_LOG_FILENAME = 'kinski.log'

