DEFAULT_VERBOSITY   = True
DEFAULT_LOG_DIR     = '/var/log'
DEFAULT_WORKING_DIR = '/tmp'

DEFAULT_HERZOG_HOST = 'euclid'

DEFAULT_HERZOG_PORT = 8001
HERZOG_LOG_FILENAME = 'herzog.log'

DEFAULT_KINSKI_PORT = 8002
KINSKI_LOG_FILENAME = 'kinski.log'

